

if (NOT FUNCTIONS_INCLUDED)
    set(FUNCTIONS_INCLUDED TRUE)
    function(print_stats)
        message(STATUS "C Compiler: ${CMAKE_C_COMPILER}")
        message(STATUS "C++ Compiler: ${CMAKE_CXX_COMPILER}")
        message(STATUS "C++ Compiler ID: ${CMAKE_CXX_COMPILER_ID}")
        message(STATUS "C Compiler ID: ${CMAKE_C_COMPILER_ID}")
        message(STATUS "C++ Compiler Version: ${CMAKE_CXX_COMPILER_VERSION}")
        message(STATUS "System Name: ${CMAKE_SYSTEM_NAME}")
        message(STATUS "System Processor: ${CMAKE_SYSTEM_PROCESSOR}")
        message(STATUS "Generator Platform: ${CMAKE_GENERATOR_PLATFORM}")
        message(STATUS "Build type: ${CMAKE_BUILD_TYPE}")
    endfunction()

    function(set_compiler_flags)
        set(BUILD_SHARED_LIBS OFF)
        add_definitions(-D_GLIBCXX_USE_CXX11_ABI=1)

        if (MSVC)
            set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>" PARENT_SCOPE)
        endif()

        if(CMAKE_SYSTEM_NAME STREQUAL "Windows")
            if(CMAKE_BUILD_TYPE STREQUAL "Release")
                set(BUILD_SHARED_LIBS OFF)
                set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -static-libgcc -static-libstdc++ -static" PARENT_SCOPE)
                set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -static-libgcc -static-libstdc++ -static" PARENT_SCOPE)
                if (CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
                    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /Z7" PARENT_SCOPE)
                    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /debug" PARENT_SCOPE)
                    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /O2 /wd4068" PARENT_SCOPE)
                elseif(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
                    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -static" PARENT_SCOPE)
                    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O3 -Wno-multichar -Wno-unused-parameter" PARENT_SCOPE)
                elseif (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
                    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -static" PARENT_SCOPE)
                    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O3 -Wno-multichar -Wno-unused-parameter" PARENT_SCOPE)
                endif ()
            elseif (CMAKE_BUILD_TYPE STREQUAL "Debug")
                if (CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
                    string(REPLACE "/RTC1" "" CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG}" PARENT_SCOPE)
                    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /Z7" PARENT_SCOPE)
                    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /debug" PARENT_SCOPE)
                elseif(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
                    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O0 -Wno-multichar -Wno-unused-parameter" PARENT_SCOPE)
                elseif (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
                    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O0 -Wno-multichar -Wno-unused-parameter" PARENT_SCOPE)
                endif ()
            endif ()
        elseif (CMAKE_SYSTEM_NAME STREQUAL "Linux")
            if(CMAKE_BUILD_TYPE STREQUAL "release")
                if(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
                    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O3 -Wno-multichar -Wno-unused-parameter" PARENT_SCOPE)
                elseif (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
                    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O3 -Wno-multichar -Wno-unused-parameter" PARENT_SCOPE)
                endif ()
            elseif (CMAKE_BUILD_TYPE STREQUAL "Debug")
                if (CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
                elseif(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
                    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O0 -Wno-multichar -Wno-unused-parameter" PARENT_SCOPE)
                    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Wextra -pedantic" PARENT_SCOPE)
                elseif (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
                    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Wextra -pedantic" PARENT_SCOPE)
                    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O0 -Wno-multichar -Wno-unused-parameter" PARENT_SCOPE)
                    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -fsanitize=address" PARENT_SCOPE)
                    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsanitize=address  -fno-omit-frame-pointer -g -O3" PARENT_SCOPE)
                endif ()
            endif ()
        endif ()
    endfunction()
endif ()
